name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We welcome feature suggestions! Please describe your idea.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - New Language Support (e.g., ZH→EN, ZH→KR)
        - Performance Optimization
        - File Format Support (e.g., .xlsx)
        - Quality Assurance Enhancement
        - Glossary Management
        - Documentation Improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Currently, users cannot..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to solve this?
      placeholder: "Add a new script that..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you think about?

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Assessment
      options:
        - label: This would benefit multiple language pairs
        - label: This addresses a production bottleneck
        - label: This improves cost efficiency
        - label: This enhances quality metrics
